language: android
jdk:
  - oraclejdk8
android:
  components:
      - tools
      - platform-tools
      - build-tools-25.0.2
      - android-25
      - extra-google-m2repository
      - extra-android-m2repository

before_install:
  - chmod +x gradlew

branches:
  only:
    - master

script:
  - ./gradlew clean
  - ./gradlew optimrest:check -Ptravis

notifications:
  email:
    recipients:
      - iagocanalejas@gmail.com
    on_success: change
    on_failure: change